version: "2"

services:
  sensor_sonnenbattery:
    build: .
    volumes:
      - ./code:/code
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always

